### ISSUE TITLE
Static recompilation

### ISSUE THREAD

**Issue by goolord** [z2442/daedalus#9]
copied from issues.md
>Static recompilation! Recompile instructions in advance and give them to the PSP at runtime, saving the dynarec a lot of work and in theory bringing big speedups (Mario 64 ran perfectly on a 166MHz Pentium 3 with static recompilation...)

**Comment by goolord** [comment]
so i think this is totally possible, if only because the [corn emulator](http://www.emulation64.com/files/info/964/corn.html/) was able to statically recompile at least a few games to the x86 instruction set. unfortunately, corn is closed source and abondonware, and static recompilation is obviously very hard (even when the instruction sets are similar)

**Comment by TheMrIron2** [comment]
Yes, this was definitely something we were looking into quite closely at one point with Corn as the centerpiece example. However, we've decided it's not feasible:

- As you said, it's incredibly difficult to set up a good static recompiler, even if the instruction sets are indeed very similar. There is still a lot of work involved.
- Static recompilation causes problems with self-changing or dynamic variables because as the name suggests the game is recompiled statically ahead of time (static program analysis) - unlike dynamic recompilation (dynamic program analysis). With static analysis, you don't have runtime information. This is well explained in [this Stack Overflow discussion](https://stackoverflow.com/questions/11215689/why-does-emulation-have-to-be-done-in-real-time) and [this statically recompiled NES emulator](https://andrewkelley.me/post/jamulator.html) and the conclusion in both is that it's just not really feasible to develop a competent emulator using static recompilation that will play many games.
